export type TopikQuestion = {
  id: number
  section: "vocabulary" | "grammar" | "reading"
  level: "TOPIK 1" | "TOPIK 2"
  question: string
  context?: string
  options: string[]
  correct: number
  explanation: string
}

export const topikQuestions: TopikQuestion[] = [
  {
    id: 1,
    section: "vocabulary",
    level: "TOPIK 1",
    question: "다음 중 '안녕하세요'와 같은 의미는? (Câu nào có nghĩa giống '안녕하세요'?)",
    options: ["감사합니다", "처음 뵙겠습니다", "안녕히 계세요", "반갑습니다"],
    correct: 1,
    explanation: "처음 뵙겠습니다 cũng là lời chào trang trọng khi lần đầu gặp mặt, tương đương 안녕하세요 trong ngữ cảnh này.",
  },
  {
    id: 2,
    section: "vocabulary",
    level: "TOPIK 1",
    question: "빈칸에 알맞은 것을 고르세요. (Chọn từ đúng cho chỗ trống)\n'물 한 ___ 주세요.'",
    options: ["개", "잔", "권", "병"],
    correct: 1,
    explanation: "잔 là đơn vị đếm cho đồ uống trong cốc/ly. 개 = cái (đồ vật), 권 = quyển (sách), 병 = chai.",
  },
  {
    id: 3,
    section: "grammar",
    level: "TOPIK 1",
    question: "다음 중 맞는 문장을 고르세요. (Chọn câu đúng ngữ pháp)",
    options: [
      "저는 학생이에요.",
      "저가 학생이에요.",
      "나는 학생입니다.",
      "저은 학생이에요.",
    ],
    correct: 0,
    explanation: "저는 학생이에요. - Sau nguyên âm dùng 는, không dùng 은. 저가 sai vì trợ từ chủ ngữ là 이/가, nhưng với 저 phải dùng 제가 (dạng khiêm nhường).",
  },
  {
    id: 4,
    section: "vocabulary",
    level: "TOPIK 1",
    question: "'오늘'의 반대말은? (Trái nghĩa của '오늘' là gì?)",
    options: ["어제", "내일", "모레", "그저께"],
    correct: 1,
    explanation: "오늘 = hôm nay, 내일 = ngày mai. 어제 = hôm qua, 모레 = ngày kia, 그저께 = hôm kia.",
  },
  {
    id: 5,
    section: "reading",
    level: "TOPIK 1",
    context: "저는 매일 아침 7시에 일어나요. 그리고 밥을 먹고 학교에 가요.",
    question: "이 사람은 몇 시에 일어나요? (Người này thức dậy lúc mấy giờ?)",
    options: ["6시", "7시", "8시", "9시"],
    correct: 1,
    explanation: "Bài đọc ghi 매일 아침 7시에 일어나요 = mỗi sáng thức dậy lúc 7 giờ.",
  },
  {
    id: 6,
    section: "grammar",
    level: "TOPIK 1",
    question: "빈칸에 알맞은 것을 고르세요. '저는 학교___ 가요.'",
    options: ["을", "에", "이", "은"],
    correct: 1,
    explanation: "에 là trợ từ chỉ nơi chốn/hướng đi. 학교에 가요 = đi đến trường. 을/를 = tân ngữ, 이/가 = chủ ngữ, 은/는 = chủ đề.",
  },
  {
    id: 7,
    section: "vocabulary",
    level: "TOPIK 1",
    question: "다음 중 음식이 아닌 것은? (Trong các từ sau, từ nào KHÔNG phải đồ ăn?)",
    options: ["비빔밥", "김치찌개", "지하철", "냉면"],
    correct: 2,
    explanation: "지하철 = tàu điện ngầm, không phải đồ ăn. 비빔밥 = cơm trộn, 김치찌개 = canh kimchi, 냉면 = mì lạnh.",
  },
  {
    id: 8,
    section: "reading",
    level: "TOPIK 1",
    context: "오늘 날씨가 많이 더워요. 그래서 아이스크림을 먹었어요.",
    question: "왜 아이스크림을 먹었어요? (Tại sao ăn kem?)",
    options: ["배가 고파서", "날씨가 더워서", "날씨가 추워서", "아이스크림이 싸서"],
    correct: 1,
    explanation: "그래서 = vì vậy. Ngày hôm nay trời rất nóng (날씨가 많이 더워요) nên ăn kem.",
  },
  {
    id: 9,
    section: "grammar",
    level: "TOPIK 1",
    question: "'저는 커피를 마셔요'를 과거형으로 바꾸면? (Chuyển sang quá khứ?)",
    options: ["저는 커피를 마실 거예요.", "저는 커피를 마셨어요.", "저는 커피를 마시고 싶어요.", "저는 커피를 마시겠어요."],
    correct: 1,
    explanation: "마시다 (uống) + -었어요 = 마셨어요 (đã uống). Đây là thì quá khứ trong tiếng Hàn, tương đương 'đã' trong tiếng Việt.",
  },
  {
    id: 10,
    section: "vocabulary",
    level: "TOPIK 1",
    question: "'크다'의 반대말은? (Trái nghĩa của '크다' là?)",
    options: ["작다", "높다", "많다", "넓다"],
    correct: 0,
    explanation: "크다 = lớn/to, 작다 = nhỏ/bé. 높다 = cao, 많다 = nhiều, 넓다 = rộng.",
  },
  {
    id: 11,
    section: "reading",
    level: "TOPIK 1",
    context: "저는 한국어를 공부해요. 한국어는 조금 어렵지만 재미있어요.",
    question: "이 사람의 한국어 공부에 대한 생각은? (Ý kiến của người này về việc học tiếng Hàn?)",
    options: ["어렵고 재미없어요", "쉽고 재미있어요", "어렵지만 재미있어요", "쉽고 재미없어요"],
    correct: 2,
    explanation: "-지만 = nhưng/tuy nhiên. 조금 어렵지만 재미있어요 = hơi khó nhưng thú vị.",
  },
  {
    id: 12,
    section: "grammar",
    level: "TOPIK 1",
    question: "다음 중 맞는 표현을 고르세요. (Chọn cách diễn đạt đúng)",
    options: ["저는 사과을 먹어요.", "저는 사과를 먹어요.", "저는 사과가 먹어요.", "저는 사과는 먹어요."],
    correct: 1,
    explanation: "사과 kết thúc bằng nguyên âm nên dùng trợ từ 를 (không phải 을). 사과를 먹어요 = ăn táo.",
  },
  {
    id: 13,
    section: "vocabulary",
    level: "TOPIK 1",
    question: "'병원'에 가는 이유로 알맞은 것은? (Lý do đúng để đi '병원'?)",
    options: ["책을 빌리러", "밥을 먹으러", "아파서", "쇼핑하러"],
    correct: 2,
    explanation: "병원 = bệnh viện. Người ta đến bệnh viện vì bị bệnh (아파서). 책 빌리기 = mượn sách (도서관), 쇼핑 = mua sắm (백화점).",
  },
  {
    id: 14,
    section: "reading",
    level: "TOPIK 1",
    context: "저는 주말에 친구를 만났어요. 우리는 영화를 보고 식당에서 밥을 먹었어요.",
    question: "주말에 무엇을 했어요? (Cuối tuần đã làm gì?)",
    options: [
      "혼자 공부했어요",
      "친구와 영화를 보고 밥을 먹었어요",
      "집에서 쉬었어요",
      "친구 집에서 잤어요",
    ],
    correct: 1,
    explanation: "Bài đọc: gặp bạn bè, xem phim, rồi ăn ở nhà hàng. 친구를 만나다 = gặp bạn, 영화를 보다 = xem phim.",
  },
  {
    id: 15,
    section: "grammar",
    level: "TOPIK 1",
    question: "빈칸에 알맞은 것을 고르세요. '지금 뭐 ___?'",
    options: ["해요", "할게요", "했어요", "할 거예요"],
    correct: 0,
    explanation: "해요 là thì hiện tại. 지금 = bây giờ, nên dùng hiện tại 해요 = đang làm gì. 했어요 = đã làm, 할 거예요 = sẽ làm.",
  },
  {
    id: 16,
    section: "vocabulary",
    level: "TOPIK 2",
    question: "'취미'의 의미는? (Nghĩa của '취미' là gì?)",
    options: ["công việc", "sở thích", "mục tiêu", "thói quen"],
    correct: 1,
    explanation: "취미 = sở thích/hobby. 직업/일 = công việc, 목표 = mục tiêu, 습관 = thói quen.",
  },
  {
    id: 17,
    section: "grammar",
    level: "TOPIK 2",
    question: "빈칸에 알맞은 것을 고르세요. '비가 오___ 우산을 가져왔어요.'",
    options: ["니까", "지만", "려고", "서"],
    correct: 3,
    explanation: "-아/어서 chỉ nguyên nhân. 비가 오다 + 아서 = 비가 와서 = vì trời mưa. Dùng khi nguyên nhân và kết quả liên tiếp tự nhiên.",
  },
  {
    id: 18,
    section: "reading",
    level: "TOPIK 2",
    context: "건강을 위해서 매일 운동을 하는 것이 좋습니다. 특히 아침 운동은 하루를 활기차게 시작할 수 있게 해 줍니다.",
    question: "이 글의 중심 내용은? (Ý chính của đoạn văn?)",
    options: [
      "운동 종류를 소개해요",
      "건강을 위해 매일 운동하는 것을 권장해요",
      "아침에 일어나는 방법을 알려줘요",
      "운동 시간을 정하는 방법이에요",
    ],
    correct: 1,
    explanation: "Nội dung chính: tập thể dục mỗi ngày tốt cho sức khỏe (건강을 위해서 매일 운동을 하는 것이 좋습니다), đặc biệt buổi sáng giúp bắt đầu ngày tích cực.",
  },
  {
    id: 19,
    section: "vocabulary",
    level: "TOPIK 2",
    question: "다음 중 '증가하다'와 반대 의미인 것은? (Trái nghĩa của '증가하다'?)",
    options: ["늘다", "오르다", "감소하다", "높아지다"],
    correct: 2,
    explanation: "증가하다 = tăng lên. 감소하다 = giảm xuống (trái nghĩa). 늘다/오르다/높아지다 đều có nghĩa tăng.",
  },
  {
    id: 20,
    section: "grammar",
    level: "TOPIK 2",
    question: "'그 영화는 매우 감동적이었다'에서 '감동적이다'의 의미는?",
    options: ["buồn cười", "đáng sợ", "cảm động/xúc động", "nhàm chán"],
    correct: 2,
    explanation: "감동 = cảm xúc/xúc động. 감동적이다 = cảm động, chạm đến trái tim. 영화 = phim, 매우 = rất.",
  },
]

export const topikSections = {
  vocabulary: topikQuestions.filter((q) => q.section === "vocabulary"),
  grammar: topikQuestions.filter((q) => q.section === "grammar"),
  reading: topikQuestions.filter((q) => q.section === "reading"),
}
